import React from "react";
import "primeflex/primeflex.css";
import "primeicons/primeicons.css";
import "primereact/resources/themes/lara-light-blue/theme.css";
import styles from "./ListadeProdutos2.module.css";
import Esporte1 from "../Slides/Esporte";
import MeuComponente2 from "./CardDinamico2";
import FilterSidebar from "./FilterSidebar";
import { useLocation, useNavigate } from "react-router-dom";

const ProducListing = ({ searchTerm }) => {
  const navigate = useNavigate();

  // Supondo que você tenha uma lista de produtos em algum estado ou props
  const products = [
    {
      id: 1,
      name: "Tênis K-Swiss V1 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 2,
      name: "Tênis K-Swiss V2 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 3,
      name: "Tênis K-Swiss V3 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 4,
      name: "Tênis K-Swiss V4 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 5,
      name: "Tênis K-Swiss V5 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 6,
      name: "Tênis K-Swiss V6 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 7,
      name: "Tênis K-Swiss V7 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 8,
      name: "Tênis K-Swiss V8 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 9,
      name: "Tênis K-Swiss V9 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 10,
      name: "Tênis K-Swiss V10 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 11,
      name: "Tênis K-Swiss V11 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 12,
      name: "Tênis K-Swiss V12 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 13,
      name: "Tênis K-Swiss V13 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 14,
      name: "Tênis K-Swiss V14 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 15,
      name: "Tênis K-Swiss V15 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 16,
      name: "Tênis K-Swiss V16 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 17,
      name: "Tênis K-Swiss V17 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 18,
      name: "Tênis K-Swiss V18 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 19,
      name: "Tênis K-Swiss V19 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 20,
      name: "Tênis K-Swiss V20 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 21,
      name: "Tênis K-Swiss V21 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 22,
      name: "Tênis K-Swiss V22 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 23,
      name: "Tênis K-Swiss V23 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 24,
      name: "Tênis K-Swiss V24 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 25,
      name: "Tênis K-Swiss V25 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 26,
      name: "Tênis K-Swiss V26 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 27,
      name: "Tênis K-Swiss V27 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 28,
      name: "Tênis K-Swiss V28 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 29,
      name: "Tênis K-Swiss V29 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 30,
      name: "Tênis K-Swiss V30 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 31,
      name: "Tênis K-Swiss V31 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 32,
      name: "Tênis K-Swiss V32 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 33,
      name: "Tênis K-Swiss V33 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 34,
      name: "Tênis K-Swiss V34 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 35,
      name: "Tênis K-Swiss V35 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 36,
      name: "Tênis K-Swiss V36 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 37,
      name: "Tênis K-Swiss V37 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 38,
      name: "Tênis K-Swiss V38 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 39,
      name: "Tênis K-Swiss V39 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 40,
      name: "Tênis K-Swiss V40 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 41,
      name: "Tênis K-Swiss V41 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 42,
      name: "Tênis K-Swiss V42 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 43,
      name: "Tênis K-Swiss V43 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 44,
      name: "Tênis K-Swiss V44 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 45,
      name: "Tênis K-Swiss V45 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 46,
      name: "Tênis K-Swiss V46 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 47,
      name: "Tênis K-Swiss V47 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 48,
      name: "Tênis K-Swiss V48 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 49,
      name: "Tênis K-Swiss V49 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 50,
      name: "Tênis K-Swiss V50 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 51,
      name: "Tênis K-Swiss V51 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 52,
      name: "Tênis K-Swiss V52 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 53,
      name: "Tênis K-Swiss V53 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 54,
      name: "Tênis K-Swiss V54 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 55,
      name: "Tênis K-Swiss V55 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 56,
      name: "Tênis K-Swiss V56 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 57,
      name: "Tênis K-Swiss V57 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 58,
      name: "Tênis K-Swiss V58 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 59,
      name: "Tênis K-Swiss V59 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 60,
      name: "Tênis K-Swiss V60 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 61,
      name: "Tênis K-Swiss V61 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 62,
      name: "Tênis K-Swiss V62 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 63,
      name: "Tênis K-Swiss V63 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 64,
      name: "Tênis K-Swiss V64 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 65,
      name: "Tênis K-Swiss V65 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 66,
      name: "Tênis K-Swiss V66 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 67,
      name: "Tênis K-Swiss V67 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 68,
      name: "Tênis K-Swiss V68 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 69,
      name: "Tênis K-Swiss V69 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 70,
      name: "Tênis K-Swiss V70 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 71,
      name: "Tênis K-Swiss V71 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 72,
      name: "Tênis K-Swiss V72 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 73,
      name: "Tênis K-Swiss V73 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 74,
      name: "Tênis K-Swiss V74 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 75,
      name: "Tênis K-Swiss V75 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 76,
      name: "Tênis K-Swiss V76 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 77,
      name: "Tênis K-Swiss V77 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 78,
      name: "Tênis K-Swiss V78 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 79,
      name: "Tênis K-Swiss V79 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 80,
      name: "Tênis K-Swiss V80 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 81,
      name: "Tênis K-Swiss V81 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 82,
      name: "Tênis K-Swiss V82 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 83,
      name: "Tênis K-Swiss V83 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 84,
      name: "Tênis K-Swiss V84 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 85,
      name: "Tênis K-Swiss V85 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 86,
      name: "Tênis K-Swiss V86 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 87,
      name: "Tênis K-Swiss V87 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 88,
      name: "Tênis K-Swiss V88 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 89,
      name: "Tênis K-Swiss V89 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 90,
      name: "Tênis K-Swiss V90 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 91,
      name: "Tênis K-Swiss V91 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 92,
      name: "Tênis K-Swiss V92 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 93,
      name: "Tênis K-Swiss V93 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 94,
      name: "Tênis K-Swiss V94 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 95,
      name: "Tênis K-Swiss V95 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 96,
      name: "Tênis K-Swiss V96 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 97,
      name: "Tênis K-Swiss V97 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 98,
      name: "Tênis K-Swiss V98 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 99,
      name: "Tênis K-Swiss V99 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 100,
      name: "Tênis K-Swiss V100 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 101,
      name: "Tênis K-Swiss V101 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 102,
      name: "Tênis K-Swiss V102 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 103,
      name: "Tênis K-Swiss V103 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 104,
      name: "Tênis K-Swiss V104 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 105,
      name: "Tênis K-Swiss V105 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 106,
      name: "Tênis K-Swiss V106 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 107,
      name: "Tênis K-Swiss V107 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 108,
      name: "Tênis K-Swiss V108 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 109,
      name: "Tênis K-Swiss V109 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 110,
      name: "Tênis K-Swiss V110 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 111,
      name: "Tênis K-Swiss V111 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 112,
      name: "Tênis K-Swiss V112 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 113,
      name: "Tênis K-Swiss V113 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 114,
      name: "Tênis K-Swiss V114 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 115,
      name: "Tênis K-Swiss V115 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 116,
      name: "Tênis K-Swiss V116 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 117,
      name: "Tênis K-Swiss V117 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 118,
      name: "Tênis K-Swiss V118 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 119,
      name: "Tênis K-Swiss V119 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 120,
      name: "Tênis K-Swiss V120 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 121,
      name: "Tênis K-Swiss V121 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 122,
      name: "Tênis K-Swiss V122 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 123,
      name: "Tênis K-Swiss V123 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 124,
      name: "Tênis K-Swiss V124 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 125,
      name: "Tênis K-Swiss V125 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 126,
      name: "Tênis K-Swiss V126 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 127,
      name: "Tênis K-Swiss V127 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 128,
      name: "Tênis K-Swiss V128 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 129,
      name: "Tênis K-Swiss V129 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 130,
      name: "Tênis K-Swiss V130 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 131,
      name: "Tênis K-Swiss V131 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 132,
      name: "Tênis K-Swiss V132 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 133,
      name: "Tênis K-Swiss V133 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 134,
      name: "Tênis K-Swiss V134 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 135,
      name: "Tênis K-Swiss V135 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 136,
      name: "Tênis K-Swiss V136 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 137,
      name: "Tênis K-Swiss V137 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 138,
      name: "Tênis K-Swiss V138 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 139,
      name: "Tênis K-Swiss V139 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 140,
      name: "Tênis K-Swiss V140 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 141,
      name: "Tênis K-Swiss V141 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 142,
      name: "Tênis K-Swiss V142 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 143,
      name: "Tênis K-Swiss V143 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 144,
      name: "Tênis K-Swiss V144 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 145,
      name: "Tênis K-Swiss V145 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 146,
      name: "Tênis K-Swiss V146 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 147,
      name: "Tênis K-Swiss V147 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 148,
      name: "Tênis K-Swiss V148 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 149,
      name: "Tênis K-Swiss V149 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 150,
      name: "Tênis K-Swiss V150 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 151,
      name: "Tênis K-Swiss V151 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 152,
      name: "Tênis K-Swiss V152 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 153,
      name: "Tênis K-Swiss V153 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 154,
      name: "Tênis K-Swiss V154 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 155,
      name: "Tênis K-Swiss V155 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 156,
      name: "Tênis K-Swiss V156 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 157,
      name: "Tênis K-Swiss V157 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 158,
      name: "Tênis K-Swiss V158 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 159,
      name: "Tênis K-Swiss V159 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 160,
      name: "Tênis K-Swiss V160 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 161,
      name: "Tênis K-Swiss V161 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 162,
      name: "Tênis K-Swiss V162 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 163,
      name: "Tênis K-Swiss V163 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 164,
      name: "Tênis K-Swiss V164 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 165,
      name: "Tênis K-Swiss V165 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 166,
      name: "Tênis K-Swiss V166 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 167,
      name: "Tênis K-Swiss V167 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 168,
      name: "Tênis K-Swiss V168 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 169,
      name: "Tênis K-Swiss V169 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 170,
      name: "Tênis K-Swiss V170 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 171,
      name: "Tênis K-Swiss V171 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 172,
      name: "Tênis K-Swiss V172 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 173,
      name: "Tênis K-Swiss V173 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 174,
      name: "Tênis K-Swiss V174 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 175,
      name: "Tênis K-Swiss V175 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 176,
      name: "Tênis K-Swiss V176 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 177,
      name: "Tênis K-Swiss V177 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 178,
      name: "Tênis K-Swiss V178 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 179,
      name: "Tênis K-Swiss V179 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 180,
      name: "Tênis K-Swiss V180 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 181,
      name: "Tênis K-Swiss V181 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 182,
      name: "Tênis K-Swiss V182 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 183,
      name: "Tênis K-Swiss V183 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 184,
      name: "Tênis K-Swiss V184 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 185,
      name: "Tênis K-Swiss V185 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 186,
      name: "Tênis K-Swiss V186 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 187,
      name: "Tênis K-Swiss V187 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 188,
      name: "Tênis K-Swiss V188 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 189,
      name: "Tênis K-Swiss V189 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 190,
      name: "Tênis K-Swiss V190 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 191,
      name: "Tênis K-Swiss V191 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 192,
      name: "Tênis K-Swiss V192 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 193,
      name: "Tênis K-Swiss V193 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 194,
      name: "Tênis K-Swiss V194 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 195,
      name: "Tênis K-Swiss V195 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 196,
      name: "Tênis K-Swiss V196 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 197,
      name: "Tênis K-Swiss V197 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 198,
      name: "Tênis K-Swiss V198 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 199,
      name: "Tênis K-Swiss V199 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 200,
      name: "Tênis K-Swiss V200 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 201,
      name: "Tênis K-Swiss V201 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 202,
      name: "Tênis K-Swiss V202 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 203,
      name: "Tênis K-Swiss V203 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 204,
      name: "Tênis K-Swiss V204 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 205,
      name: "Tênis K-Swiss V205 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 206,
      name: "Tênis K-Swiss V206 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 207,
      name: "Tênis K-Swiss V207 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 208,
      name: "Tênis K-Swiss V208 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 209,
      name: "Tênis K-Swiss V209 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 210,
      name: "Tênis K-Swiss V210 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 211,
      name: "Tênis K-Swiss V211 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 212,
      name: "Tênis K-Swiss V212 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 213,
      name: "Tênis K-Swiss V213 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 214,
      name: "Tênis K-Swiss V214 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 215,
      name: "Tênis K-Swiss V215 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 216,
      name: "Tênis K-Swiss V216 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 217,
      name: "Tênis K-Swiss V217 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 218,
      name: "Tênis K-Swiss V218 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 219,
      name: "Tênis K-Swiss V219 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 220,
      name: "Tênis K-Swiss V220 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 221,
      name: "Tênis K-Swiss V221 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 222,
      name: "Tênis K-Swiss V222 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 223,
      name: "Tênis K-Swiss V223 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 224,
      name: "Tênis K-Swiss V224 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 225,
      name: "Tênis K-Swiss V225 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 226,
      name: "Tênis K-Swiss V226 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 227,
      name: "Tênis K-Swiss V227 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 228,
      name: "Tênis K-Swiss V228 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 229,
      name: "Tênis K-Swiss V229 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 230,
      name: "Tênis K-Swiss V230 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 231,
      name: "Tênis K-Swiss V231 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 232,
      name: "Tênis K-Swiss V232 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 233,
      name: "Tênis K-Swiss V233 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 234,
      name: "Tênis K-Swiss V234 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 235,
      name: "Tênis K-Swiss V235 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 236,
      name: "Tênis K-Swiss V236 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 237,
      name: "Tênis K-Swiss V237 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 238,
      name: "Tênis K-Swiss V238 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 239,
      name: "Tênis K-Swiss V239 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 240,
      name: "Tênis K-Swiss V240 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 241,
      name: "Tênis K-Swiss V241 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 242,
      name: "Tênis K-Swiss V242 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 243,
      name: "Tênis K-Swiss V243 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 244,
      name: "Tênis K-Swiss V244 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 245,
      name: "Tênis K-Swiss V245 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 246,
      name: "Tênis K-Swiss V246 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 247,
      name: "Tênis K-Swiss V247 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 248,
      name: "Tênis K-Swiss V248 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 249,
      name: "Tênis K-Swiss V249 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 250,
      name: "Tênis K-Swiss V250 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 251,
      name: "Tênis K-Swiss V251 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 252,
      name: "Tênis K-Swiss V252 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 253,
      name: "Tênis K-Swiss V253 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 254,
      name: "Tênis K-Swiss V254 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 255,
      name: "Tênis K-Swiss V255 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 256,
      name: "Tênis K-Swiss V256 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 257,
      name: "Tênis K-Swiss V257 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 258,
      name: "Tênis K-Swiss V258 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 259,
      name: "Tênis K-Swiss V259 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 260,
      name: "Tênis K-Swiss V260 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 261,
      name: "Tênis K-Swiss V261 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 262,
      name: "Tênis K-Swiss V262 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 263,
      name: "Tênis K-Swiss V263 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 264,
      name: "Tênis K-Swiss V264 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 265,
      name: "Tênis K-Swiss V265 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 266,
      name: "Tênis K-Swiss V266 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 267,
      name: "Tênis K-Swiss V267 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 268,
      name: "Tênis K-Swiss V268 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 269,
      name: "Tênis K-Swiss V269 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 270,
      name: "Tênis K-Swiss V270 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 271,
      name: "Tênis K-Swiss V271 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 272,
      name: "Tênis K-Swiss V272 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 273,
      name: "Tênis K-Swiss V273 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 274,
      name: "Tênis K-Swiss V274 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 275,
      name: "Tênis K-Swiss V275 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 276,
      name: "Tênis K-Swiss V276 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 277,
      name: "Tênis K-Swiss V277 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 278,
      name: "Tênis K-Swiss V278 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 279,
      name: "Tênis K-Swiss V279 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 280,
      name: "Tênis K-Swiss V280 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 281,
      name: "Tênis K-Swiss V281 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 282,
      name: "Tênis K-Swiss V282 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 283,
      name: "Tênis K-Swiss V283 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 284,
      name: "Tênis K-Swiss V284 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 285,
      name: "Tênis K-Swiss V285 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 286,
      name: "Tênis K-Swiss V286 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 287,
      name: "Tênis K-Swiss V287 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 288,
      name: "Tênis K-Swiss V288 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 289,
      name: "Tênis K-Swiss V289 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 290,
      name: "Tênis K-Swiss V290 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 291,
      name: "Tênis K-Swiss V291 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 292,
      name: "Tênis K-Swiss V292 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 293,
      name: "Tênis K-Swiss V293 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 294,
      name: "Tênis K-Swiss V294 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 295,
      name: "Tênis K-Swiss V295 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 296,
      name: "Tênis K-Swiss V296 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 297,
      name: "Tênis K-Swiss V297 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 298,
      name: "Tênis K-Swiss V298 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 299,
      name: "Tênis K-Swiss V299 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
    {
      id: 300,
      name: "Tênis K-Swiss V300 - Masculino",
      category: "Esporte",
      price: "$100",
      originalPrice: "$200",
    },
  ];

  const filteredProducts = products.filter((product) =>
    product.name.toLowerCase().includes(searchTerm.toLowerCase())
  );

  const handleProductClick = (productname) => {
    navigate(`/detalhes/${productname}`);
  };

  const handleRelatedProductsClick = () => {
    setTimeout(() => {
      window.scrollTo({
        top: 0,
        behavior: "smooth",
      });
    }, 100);
  };

  const location = useLocation();
  const queryParams = new URLSearchParams(location.search);

  return (
    <MeuComponente2>
      <div className="pb-7 pt-7 surface-100">
        <h2 className="m-0 text-xl font-bold ml-6">
          Resultados para {searchTerm} - {filteredProducts.length} produtos
        </h2>
      </div>
      <div className="flex flex-row">
        <div className="surface-100">
          <FilterSidebar />
        </div>

        <section className="overflow-hidden px-1 flex-1 surface-100">
          <div className="flex w-11 justify-content-end align-items-center ml-4 pb-8">
            <select className="custom-select text-2xl p-dropdown p-component surface-100 pb-3 shadow-4 border-round-md mr-5">
              <option value="price-asc">Preço: Menor para Maior</option>
              <option value="price-desc">Preço: Maior para Menor</option>
              <option value="newest">Mais Recentes</option>
              <option value="relevance">Mais Relevantes</option>
            </select>
          </div>

          <div className="flex justify-content-center md:px-4 w-full">
            <div
              id="related-products"
              className="flex flex-wrap justify-content-center gap-6"
              onClick={() => handleRelatedProductsClick()}
            >
              {filteredProducts.slice(0, 12).map((product, index) => (
                <div
                  className={`${styles.productImage} cursor-pointer`}
                  key={product.id}
                  onClick={() => handleProductClick(product.name)}
                >
                  <div
                    className={styles.productImage}
                    style={{
                      position: "absolute",
                      background: "white",
                      padding: "1rem",
                      textAlign: "center",
                      borderRadius: "2%",
                    }}
                  >
                    <Esporte1 style={{ width: "100%", height: "auto" }} />
                    {index < 2 && (
                      <h4 className="absolute top-0 right-1 bg-green-300 w-3 ml-5 border-round-3xl z-20">
                        30% OFF
                      </h4>
                    )}
                  </div>
                  <div
                    className="cursor-pointer"
                    style={{ paddingTop: "1rem" }}
                  >
                    <h6
                      style={{ marginTop: "17.5rem", marginBottom: "0.5rem" }}
                    >
                      Tênis
                    </h6>
                    <h2 className="text-500" style={{ margin: "0" }}>
                      {product.name}
                    </h2>
                    <div
                      style={{
                        marginLeft: "auto",
                        display: "flex",
                        alignItems: "center",
                      }}
                    >
                      <h4
                        className="text-400 text-2xl"
                        style={{
                          textDecoration: "line-through",
                          marginRight: "0.5rem",
                        }}
                      >
                        {product.originalPrice}
                      </h4>
                      <h3 className="text-2xl" style={{ margin: 0 }}>
                        {product.price}
                      </h3>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>
      </div>
    </MeuComponente2>
  );
};

export default ProducListing;
